version: "3"
services:
    nginx-react:
      image: rokiis1/sorting_visualizer:latest
      container_name: sorting_visualizer_clone
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
        - 80:80
      environment:
        NODE_ENV: production
