name: frontend CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install pnpm
      run: |
        npm install -g pnpm
    - name: Install dependencies
      run: |
        pnpm install
    - name: Lint with eslint
      run: |
        pnpm run lint
    - name: Build Container
      run: |
        docker build -t rokiis1/sorting-visualizer .